receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: localhost:4317
    insecure: true
  jaeger:
    endpoint: "http://jaeger:14250"
    insecure: true

processors:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_mib: 400
    spike_limit_mib: 50
    ballast_size_mib: 64

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
